version: '3'

vars:
  SRC_DIR: src
  HOST: 0.0.0.0
  PORT: 8080
  APP_MODULE: app.main:app  # adjust if your FastAPI app path differs

tasks:
  setup:
    desc: Set up the project using uv and pyproject.toml
    cmds:
      - uv venv
      - uv pip install -U pip setuptools wheel  # optional, for safety
      - uv pip install --extra cpu --no-deps  # optional, if you use extras
      - uv pip install -e .

  clean:
    desc: Remove caches and build artifacts
    cmds:
      - rm -rf build/
      - rm -rf dist/
      - rm -rf *.egg-info/
      - rm -rf .mypy_cache/
      - rm -rf .ruff_cache/
      - rm -rf __pycache__/
      - rm -rf {{.SRC_DIR}}/**/__pycache__/

  lint:
    desc: Run linters using ruff and mypy
    cmds:
      - uv run -- ruff check {{.SRC_DIR}}
      - uv run -- mypy {{.SRC_DIR}}

  format:
    desc: Auto-format code using ruff
    cmds:
      - uv run -- ruff format {{.SRC_DIR}}

  test:
    desc: Run tests using pytest
    cmds:
      - uv run -- pytest {{.SRC_DIR}}/tests

  start:
    desc: Start the FastAPI app using Uvicorn
    cmds:
      - uv run -- uvicorn {{.APP_MODULE}} --reload --host {{.HOST}} --port {{.PORT}}

  dev:
    desc: Run linting, formatting, and tests
    deps: [lint, format, test]

  update-deps:
    desc: Update all dependencies from pyproject.toml
    cmds:
      - uv pip install --upgrade -e .
